type SearchBookingResult {
  cars: [Car!]
  offices: [Office!]
}

type BookResult {
  booked: Boolean!
}

input SearchBookingsInput {
  user: String!
  offset: Int
  limit: Int
}

input BookCarInput {
  _id: String!
  user: String!
}

input BookOfficeInput {
  _id: String!
  user: String!
}

type Query {
  findBookings(filter: SearchBookingsInput!): SearchBookingResult!
}

type Mutation {
  toggleBookCar(bookCarInput: BookCarInput!): BookResult!
  toggleBookOffice(bookOfficeInput: BookOfficeInput!): BookResult!
}
